using Microsoft.Data.Sqlite;
using OwnerTrack.Infrastructure;
string dbPath = Path.Combine(Directory.GetCurrentDirectory(), "Firme_test.db");
string connStr = $"Data Source={dbPath}";
Console.WriteLine("Running ApplyMigrations() a SECOND time (idempotency check)...");
new SchemaManager(connStr).ApplyMigrations();
Console.WriteLine("Second run completed without error.");
using var conn = new SqliteConnection(connStr);
conn.Open();
using var cmd = conn.CreateCommand();
cmd.CommandText = "SELECT COUNT(*) FROM Klijenti";
Console.WriteLine($"Klijenti count: {cmd.ExecuteScalar()}");
